const eras=[
{era:'1960–1964',wash:'rgba(54,92,126,.43)',video:'https://player.vimeo.com/external/434045526.sd.mp4?s=6313f2e20289fbfa2cbf4af136fd9f01b25345f0&profile_id=139&oauth2_token_id=57447761',male:['Navy Yard Dungarees','https://upload.wikimedia.org/wikipedia/commons/2/28/US_Navy_100906-N-3408P-130_Aviation_Structural_Mechanic_Airman_Joseph_Borelli%2C_assigned_to_the_Argonauts_of_Patrol_Squadron_%28VP%29_4%2C_cleans_the_flight_deck_as_part_of_his_daily_duties.jpg','PSNS uniforms centered on denim utility for mechanical work.','Punch clocks kept everyone honest and caffeinated.'],female:['Clinical Nursing Whites','https://upload.wikimedia.org/wikipedia/commons/9/95/U.S._Navy_hospital_corpsmen.jpg','Crisp whites reflected formal nursing discipline and cleanliness.','A spotless collar in rain felt like a medal.']},
{era:'1965–1969',wash:'rgba(149,105,47,.38)',video:'https://player.vimeo.com/external/371433846.sd.mp4?s=2364ef52eb6ce57dc4f66cf4e6f0d95dbf2d5cde&profile_id=139&oauth2_token_id=57447761',male:['Service Station Wear','https://upload.wikimedia.org/wikipedia/commons/2/2a/Gas_station_attendant_1966.jpg','Station uniforms symbolized dependable full-service routine.','Windows were cleaned before the radio song ended.'],female:['Retail/Stewardess Professionalwear','https://upload.wikimedia.org/wikipedia/commons/a/ac/Stewardess_showing_new_uniform_1968.jpg','Tailored service uniforms carried a polished civic image.','Those hats had more weather experience than tourists.']},
{era:'1970–1979',wash:'rgba(80,84,88,.49)',video:'https://player.vimeo.com/external/445690438.sd.mp4?s=13ce2f5df5f9ed5dbc6d82af6f5d56be4bb86fd5&profile_id=139&oauth2_token_id=57447761',male:['Maritime/Logging Layers','https://upload.wikimedia.org/wikipedia/commons/b/b5/Logger%2C_Washington_state%2C_1972.jpg','Rugged gear resisted wet industrial shifts across the region.','If boots dried overnight, it was probably luck.'],female:['Shipyard Coveralls','https://upload.wikimedia.org/wikipedia/commons/1/14/Female_shipyard_worker.jpg','Women in industry used coveralls and safety-ready workwear.','Every coverall pocket carried at least one mystery washer.']}
];
const stage=document.getElementById('stage'),cursor=document.getElementById('cursor');
const scenes=eras.map((e,n)=>{const s=document.createElement('section');s.className=`scene ${n===0?'on':''}`;s.innerHTML=`<video autoplay muted loop playsinline src="${e.video}"></video><div class="wash" style="background:${e.wash}"></div><div class="wrap"><article class="shell"><section class="pane male"><div class="tag">Dock | ${e.era}</div><h2>${e.male[0]}</h2><img src="${e.male[1]}" alt="${e.male[0]}"><p>${e.male[2]}</p><button class="pop">Dock fact</button></section><section class="pane female"><div class="tag">Drape | ${e.era}</div><h2>${e.female[0]}</h2><img src="${e.female[1]}" alt="${e.female[0]}"><p>${e.female[2]}</p><button class="pop">Drape fact</button></section></article></div>`;const sh=s.querySelector('.shell');sh.onclick=x=>{if(!x.target.classList.contains('pop'))sh.classList.toggle('flip');};sh.onmouseenter=()=>cursor.classList.add('live');sh.onmouseleave=()=>cursor.classList.remove('live');s.querySelectorAll('.pop')[0].onclick=()=>alert(e.male[3]);s.querySelectorAll('.pop')[1].onclick=()=>alert(e.female[3]);stage.append(s);return s;});
document.querySelectorAll('[data-go]').forEach(b=>b.onclick=()=>{const i=Number(b.dataset.go);scenes.forEach((s,n)=>s.classList.toggle('on',n===i));});
window.onmousemove=e=>{cursor.style.left=`${e.clientX}px`;cursor.style.top=`${e.clientY}px`;};
